
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class RunCustomCommandParameters {
    /**
    * Label: Group Of commands, type: entry
    */
    String group
    /**
    * Label: Command, type: entry
    */
    String command
    /**
    * Label: Sub-command, type: textarea
    */
    String subCommands
    /**
    * Label: Options, type: textarea
    */
    String options
    /**
    * Label: Result property sheet, type: entry
    */
    String resultPropertySheet

    static RunCustomCommandParameters initParameters(StepParameters sp) {
        RunCustomCommandParameters parameters = new RunCustomCommandParameters()

        def group = sp.getRequiredParameter('group').value
        parameters.group = group
        def command = sp.getRequiredParameter('command').value
        parameters.command = command
        def subCommands = sp.getParameter('subCommands').value
        parameters.subCommands = subCommands
        def options = sp.getParameter('options').value
        parameters.options = options
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 2841349e959dd61073e1aa73bd16e69c ===
