
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class RunCustomCommandParameters {
    /**
    * Label: Group Of Commands, type: entry
    */
    String group
    /**
    * Label: Command, type: entry
    */
    String command
    /**
    * Label: Sub Command, type: textarea
    */
    String subCommands
    /**
    * Label: Options, type: textarea
    */
    String options
    /**
    * Label: Action On Error, type: select
    */
    String actionOnError
    /**
    * Label: Error Value, type: entry
    */
    String errorValue
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static RunCustomCommandParameters initParameters(StepParameters sp) {
        RunCustomCommandParameters parameters = new RunCustomCommandParameters()

        def group = sp.getRequiredParameter('group').value
        parameters.group = group
        def command = sp.getRequiredParameter('command').value
        parameters.command = command
        def subCommands = sp.getParameter('subCommands').value
        parameters.subCommands = subCommands
        def options = sp.getParameter('options').value
        parameters.options = options
        def actionOnError = sp.getRequiredParameter('actionOnError').value
        parameters.actionOnError = actionOnError
        def errorValue = sp.getParameter('errorValue').value
        parameters.errorValue = errorValue
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 007bad51fef31f471a166fbfdac23513 ===
