version: '3'
services:
  electric-flow:
    container_name: efserver
    hostname: "efserver"
    image: "us-east1-docker.pkg.dev/cloudbees-artifact-registry/flow/plugin-specs/electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    tty: true
  efagent-gcloud:
    container_name: efagent-gcloud
    image: "us-east1-docker.pkg.dev/cloudbees-artifact-registry/flow/plugin-specs/electricflow/gcloud:latest"
    hostname: "efagent-gcloud"
    ports:
      - "7808:7808"
    networks:
      - internal
    tty: true
networks:
  internal:
    driver: bridge
