version: '3'
services:
  electric-flow:
    container_name: efserver
    hostname: "efserver"
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    tty: true
  efagent-git:
    container_name: efagent-git
    image: electricflow/git:latest
    hostname: "efagent-git"
    ports:
      - "7808:7808"
    networks:
      - internal
    tty: true
networks:
  internal:
    driver: bridge
